### ISSUE TITLE
Backend in csharp

### ISSUE THREAD

**Issue by rutvi1** [PAYON-AG/copyandpay-csharp#1]
Hi,

    I created demo application in c sharp and the code is like below. Now I need Back end to check History of payment which is provided by You. So how can I access Admin back end site, Do I need to code it my self IF Yes then how, can You please provide me demo code for that?

    I have used your code for preparecheckout is:
    public string prepareCheckout()
    {
    var checkoutId = string.Empty;
    var amt = GetDecryptedPassword(Request.QueryString["amt"].ToString());
    var email = GetDecryptedPassword(Request.QueryString["email"].ToString());
    var data = new NameValueCollection() {
    {"authentication.userId", "8a8294184b4f2868014b4f86f767015d"},
    {"authentication.password", "F8T7N4PD"},
    {"authentication.entityId", "8a8294184b4f2868014b4f87bf160173"},
    {"paymentType", "DB"},
    {"amount", amt},
    {"currency", "EUR"},
    {"customer.email", email },
    };

**Comment by steve-nester-uk** [comment]
Hi; more examples are provided at https://docs.oppwa.com, including 'back office' requests.
